version: "3.9"
services:
    api:
        container_name: api
        hostname: api
        build:
            context: .
            dockerfile: FunTrophy.API/Dockerfile
        ports:
            - ${API_PORT:-8080}:80
        env_file:
            - .env
        environment:
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
        volumes:
            - ./FunTrophy.Infrastructure/FunTrophy.sqlite:/app/Infrastructure/FunTrophy.sqlite

    web:
        container_name: web
        build:
            context: .
            dockerfile: FunTrophy.Web/Dockerfile
        ports:
            - ${WEB_PORT:-80}:80
        env_file:
            - .env
        depends_on:
            - api
        environment:
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
        volumes:
            - ./FunTrophy.Web/wwwroot/appsettings.json:/usr/share/nginx/html/appsettings.json